# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdf.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdf.proto',
  package='pdf',
  syntax='proto3',
  serialized_options=b'\n\013io.grpc.pdfB\016PdfServerProtoP\001',
  serialized_pb=b'\n\tpdf.proto\x12\x03pdf\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"X\n\x13UploadResourceReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12#\n\nstatusCode\x18\x02 \x01(\x0e\x32\x0f.pdf.StatusCode\x12\x0b\n\x03uid\x18\x03 \x01(\t\"D\n\rRenderRequest\x12\x12\n\ntemplateId\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\"K\n\x0bRenderReply\x12#\n\nstatusCode\x18\x01 \x01(\x0e\x32\x0f.pdf.StatusCode\x12\x17\n\x0ftemplateVersion\x18\x02 \x01(\t\"\x1e\n\x0f\x44ownloadRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t*-\n\nStatusCode\x12\x0b\n\x07Unknown\x10\x00\x12\x06\n\x02Ok\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02\x32\xa5\x01\n\x03Pdf\x12:\n\x0euploadResource\x12\n.pdf.Chunk\x1a\x18.pdf.UploadResourceReply\"\x00(\x01\x12\x30\n\x06render\x12\x12.pdf.RenderRequest\x1a\x10.pdf.RenderReply\"\x00\x12\x30\n\x08\x64ownload\x12\x14.pdf.DownloadRequest\x1a\n.pdf.Chunk\"\x00\x30\x01\x42\x1f\n\x0bio.grpc.pdfB\x0ePdfServerProtoP\x01\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='pdf.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ok', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=313,
  serialized_end=358,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
Unknown = 0
Ok = 1
Failed = 2



_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='pdf.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='pdf.Chunk.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=42,
)


_UPLOADRESOURCEREPLY = _descriptor.Descriptor(
  name='UploadResourceReply',
  full_name='pdf.UploadResourceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pdf.UploadResourceReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='pdf.UploadResourceReply.statusCode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='pdf.UploadResourceReply.uid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=132,
)


_RENDERREQUEST = _descriptor.Descriptor(
  name='RenderRequest',
  full_name='pdf.RenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='templateId', full_name='pdf.RenderRequest.templateId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='pdf.RenderRequest.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='pdf.RenderRequest.parameters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=202,
)


_RENDERREPLY = _descriptor.Descriptor(
  name='RenderReply',
  full_name='pdf.RenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='pdf.RenderReply.statusCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='templateVersion', full_name='pdf.RenderReply.templateVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=279,
)


_DOWNLOADREQUEST = _descriptor.Descriptor(
  name='DownloadRequest',
  full_name='pdf.DownloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pdf.DownloadRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=311,
)

_UPLOADRESOURCEREPLY.fields_by_name['statusCode'].enum_type = _STATUSCODE
_RENDERREPLY.fields_by_name['statusCode'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['UploadResourceReply'] = _UPLOADRESOURCEREPLY
DESCRIPTOR.message_types_by_name['RenderRequest'] = _RENDERREQUEST
DESCRIPTOR.message_types_by_name['RenderReply'] = _RENDERREPLY
DESCRIPTOR.message_types_by_name['DownloadRequest'] = _DOWNLOADREQUEST
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'pdf_pb2'
  # @@protoc_insertion_point(class_scope:pdf.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

UploadResourceReply = _reflection.GeneratedProtocolMessageType('UploadResourceReply', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADRESOURCEREPLY,
  '__module__' : 'pdf_pb2'
  # @@protoc_insertion_point(class_scope:pdf.UploadResourceReply)
  })
_sym_db.RegisterMessage(UploadResourceReply)

RenderRequest = _reflection.GeneratedProtocolMessageType('RenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREQUEST,
  '__module__' : 'pdf_pb2'
  # @@protoc_insertion_point(class_scope:pdf.RenderRequest)
  })
_sym_db.RegisterMessage(RenderRequest)

RenderReply = _reflection.GeneratedProtocolMessageType('RenderReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREPLY,
  '__module__' : 'pdf_pb2'
  # @@protoc_insertion_point(class_scope:pdf.RenderReply)
  })
_sym_db.RegisterMessage(RenderReply)

DownloadRequest = _reflection.GeneratedProtocolMessageType('DownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADREQUEST,
  '__module__' : 'pdf_pb2'
  # @@protoc_insertion_point(class_scope:pdf.DownloadRequest)
  })
_sym_db.RegisterMessage(DownloadRequest)


DESCRIPTOR._options = None

_PDF = _descriptor.ServiceDescriptor(
  name='Pdf',
  full_name='pdf.Pdf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=361,
  serialized_end=526,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadResource',
    full_name='pdf.Pdf.uploadResource',
    index=0,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_UPLOADRESOURCEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='render',
    full_name='pdf.Pdf.render',
    index=1,
    containing_service=None,
    input_type=_RENDERREQUEST,
    output_type=_RENDERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='pdf.Pdf.download',
    index=2,
    containing_service=None,
    input_type=_DOWNLOADREQUEST,
    output_type=_CHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PDF)

DESCRIPTOR.services_by_name['Pdf'] = _PDF

# @@protoc_insertion_point(module_scope)
